### ISSUE TITLE
CliC-it 2023

### ISSUE THREAD

**Issue by MariaLauraP** [openreview/openreview#103]
OpenReview didn't work this morning, I couldn't accomplish with my registration in order to submit a proposal to CliC-it 2023 as one of the authors. Please, find attached a screenshot
![Schermata 2023-07-31 alle 09 40 36](https://github.com/openreview/openreview/assets/141015600/1f14e2f6-a8de-4499-92c7-42a2dcaae63f)
I hope this issue won't be a reason for exclusion...
Please let it know to the Organizing Committee of the conference

**Comment by carlosmondra** [comment]
Hello @MariaLauraP 

Thanks for reporting this. We didn't receive any notifications of the API being down. There may be several reasons why this happened to you. It could have been a network issue, in which case, waiting a couple of minutes and trying again or switching to a different network would make the site work. There are also other web services you can use to check if the OpenReview API is indeed down for everyone or just a network issue.

Could you please let me know if you try again or if you are able to access the site now?

You can also get in touch with the organizers in such cases, so that they can check whether the site was actually down or not and then they can tell you how to proceed.

**Comment by melisabok** [comment]
Closing this issue because no error was found in the API.
