### ISSUE TITLE
[Feature request] Add option to respond with reduced load on first invitation to reviewers

### ISSUE THREAD

**Issue by adinriv** [openreview/openreview#104]
**Is your feature request related to a problem? Please describe.**
The invitation workflow requires the invited reviewer to decline the invitation and then select to participate with a reduced load.  This process is unintuitive and cumbersome on the reviewer.

**Describe the solution you'd like**
Instead, the should be an option (perhaps another link) to accept the invitation with a reduced load (if given the option on the form) right away from the original invitation email.

**Describe alternatives you've considered**
The alternative is to add a sentence in the invitation email explaining that if the reviewer wants a reduced load they need to reject the invitation and select that option.

**Comment by melisabok** [comment]
This request must come from venue organizers. 

They decide when they want to accept a reduced quota.

**Comment by adinriv** [comment]
Apologies for not been clear from the description.  This flow that I described is from the point of view of a venue organizer.  

I'm inviting the reviewers and want to give them the chance of accept with a reduced load right away instead of having to decline the invitation and then do accepting with a reduced load.  

This process is unintuitive for the reviewers and obfuscates a process that could be transparent.

For instance, there could be an option on the "Invitee reduced load" in which you have the two step process or send it in the default template.  For example, the email template could parse a `{{reduced_load_invitation_url}}` parameter to default into the reduced load invitation.

**Comment by melisabok** [comment]
Thanks for the explanation. 

@xkopenreview what do you think about supporting the reduce quota dropdown when accepting the invitation?

@adinriv which is the venue that you are organizing and when do you need to have this working?

**Comment by adinriv** [comment]
I'm organizing the NLDL 2024.  

As you suggest in your comment, having an option to add the reduced load on acceptance will be the best solution.  This will also require to update the default templates to reflect the change.

**Comment by xkopenreview** [comment]
Hi Adin,

please let us know if this fits the workflow you have in mind:
PCs can add a new config variable in recruitment invitation.
when it's set to true, the recruitment page will show a accept with reduced load button
![image](https://github.com/openreview/openreview/assets/60613434/66d07968-879e-48a3-90e9-78c4ff9da8bb)

when invitee click on the accept with reduced load button, the user will be shown the reduced load dropdown and a button to submit the response.
while the logic flow of invitee clicking on reject remains the same. they will still see the link to request reduced load.

thanks

**Comment by xkopenreview** [comment]
> That is a good compromise. Perhaps adding some information that there will be further instructions with the reduce load after accepting. It is not intuitive that that will be the case with the image you show now.

do you mean in the text above the buttons? the "please respond to this invitation by choosing one of the options below"?
the text (including the text above it "You have been invited...") can be set in invitationMessage which is a property in the config.

please let us know if it's what you need.
thanks

**Comment by adinriv** [comment]
I was talking about the information about selecting the load while clicking the "Accept with reduced load".  From the final user perspective, it is difficult to know what will happen when clicking the button and what load are they accepting.  Perhaps having a tool tip on the button with some customizable information in the lines of "Once accepted the reduced load you will be able to select the quota as set up by the venue."  or something like that.

Regarding the buttons for the reduced load, it is good to have the buttons as you showed them.

**Comment by xkopenreview** [comment]
> I was talking about the information about selecting the load while clicking the "Accept with reduced load".

hi @adinriv 

the text above the buttons are set in the config by member of program chairs group and it can be arbitrary markdown text.
in the screenshot below i modified the config to add some explanations of the function of each button
so if a venue enable accept with reduced load function the PC will need to update the text above the buttons accordingly because the accept with reduced load function is by default disabled.

<img width="902" alt="image" src="https://github.com/openreview/openreview/assets/60613434/5c535a3c-d0c9-4e5c-9163-2b29ee283837">

please let us know if this is what you need.
thanks.

**Comment by adinriv** [comment]
Excellent!

As long as there is a way to update it, it will be Ok.

Would the toggle of the button trigger the update of the configuration as well?  Or will it require some manual changes?  If it is the latter, then having some tool tip on the configuration side explaining how to set it up will be helpful (instead of letting the one configuring it figuring out how to change it).

**Comment by xkopenreview** [comment]
hi @adinriv 

the instruction text is not updated automatically based on whether accept with reduced load is enabled because each venue will probably want to show some different instructions.

currently we don't yet have instruction about updating the instruction text while it's almost a one-to-one mapping of text from the config to the screen. when you have questions that is not covered in the documentation you can always email your question to info@openreview.net and someone will help you with any issue/difficulty that you are facing.

changes for the feature to allow accept with reduced load is now under review but we don't yet have a time when this change will be deployed. we will update you once it's deployed so we can help you with updating the instructions markdown of your venue.

thanks.

**Comment by adinriv** [comment]
Thanks for the update.

**Comment by melisabok** [comment]
@xkopenreview can you confirm this issue is fixed?
