### ISSUE TITLE
"Education history": no more than 2 MS allowed?

### ISSUE THREAD

**Issue by v-alentina** [openreview/openreview#119]
I am creating my profile. I would like to insert 3 master's degrees in the "Education & Carrier History" but, when i click "Save", only 2 are shown on my profile.

This is the history I tried to upload:
![image](https://github.com/openreview/openreview/assets/148249218/a32401e5-3536-4596-9f26-bc1e434ce2c5)

...and this is my current profile after saving:
https://openreview.net/profile?id=~Valentina_Decembrini1

I also tried different order combinations, 1 MS is being cut off.

Thank you for the support!

**Comment by melisabok** [comment]
I think the system is joining the first and last row because they are coming from the same institution domain. 

The department name is different so it should be keep both row independently. 

We will fix this soon. 

@carlosmondra I think the inference should take into account the department name to distinguish the different institutions.

**Comment by melisabok** [comment]
This is deployed in the live site, @v-alentina please try again and let us know if you find any issues.

**Comment by v-alentina** [comment]
It works perfectly, thank you!!
