### ISSUE TITLE
Reporting an Issue with Author Registration of Openreview

### ISSUE THREAD

**Issue by XYLGroup** [openreview/openreview#134]
**Describe the bug**
When we intend to submit to CVPR2024, a author has submitted the registration application and completed the information more than 12 hours ago. However, the author's account has not been activated yet.

**Comment by carlosmondra** [comment]
Due to the amount of sign ups that we are now receiving, we have updated that to be a max of 2 weeks. Usually the process doesn't take this long, but we try to filter out fake profiles. Using an OpenReview registered institutional email (from an academic institution, company, etc.) gets the profile approved immediately.
