### ISSUE TITLE
Erroe

### ISSUE THREAD

**Issue by ckbaru** [openreview/openreview#38]
**Describe the bug**
I am trying to create a new venue, and I keep getting this error message: "Author identities of withdrawn submissions can only be anonymized for double-blind submissions" What does it mean and how do i fix it?? My venue is single-blind submission.

**To Reproduce**
1.. Try to create a venue with single-blind. that's it. 

**Expected behavior**
I expec the submission to go through!

**Screenshots**
I have the screenshot. How do i submit it!

**Device information (please complete the following information):**
 
 - Browser [FireFox]
 - Version [103.0]

**Additional context**
Tried various radio button settings. Nothing seems to work

**Comment by nlbahy** [comment]
It sounds like the issue is caused by the fact that you have this option selected: "No, author identities of withdrawn submissions should not be revealed." This is not possible in a single-blind venue, since no author identities will be hidden. Similarly, you will need to select "Yes, author identities of desk rejected submissions should be revealed." for the field "Desk Rejected Submissions Author Anonymity". Please let us know if you run into any further issues at info@openreview.net.
