### ISSUE TITLE
Allow authors to choose how their name will be displayed

### ISSUE THREAD

**Issue by djvanderlaan** [openreview/openreview#67]
This might be a duplicate of issue #21 although that issue focuses on the fact that not all names can be split into fist and last names. This issue is about more flexibility in first names.  This might mean there should be a more general issue about the flexibility in names. 

In some languages (Dutch and I know Spanish has this also) the first first name is not always the name used to address a person. In my case my initials are "D. J." while I would preferred to be called "Jan". In my case "Jan" happens to be my second first name, but this is not always the case. For example my sisters initials are "E.H." and she is called "Lisette". Currently the system calls me "Dingeman". 

For papers etc I would like the system to use my full name "D. J. [lastname]" or "Dingeman Jan [lastname]"., but as soon as only one first name is used I would like the system to use "Jan [lastname]".  So perhaps a "How should we call you?" field would work? 

Minor point: a lot of people have more than 2 first names. Of course one can type in more than one name in the "middle name" field. Perhaps change the name of that field to "middle name**s**".

A more general solution would perhaps be to have a "full name field" where one can type in all first names and a "first name field" for the first name that should be used to call someone.

**Comment by carlosmondra** [comment]
Hi @djvanderlaan ,

We have started to use a full name field instead of first, middle and last name fields. This seemed to be the most reasonable way to accommodate all the different ways in which names are written around the world.

OpenReview allows users to add multiple names to their profiles and set one of them as preferred. The preferred name will be used in papers and emails to address you.

We discussed having a field "how do you want to be called?", but decided that the preferred name field is sufficient for this feature.
