### ISSUE TITLE
"Username not found"

### ISSUE THREAD

**Issue by yuri-bizzoni** [openreview/openreview#91]
**Describe the bug**
I have an account for [REMOVED] but it doesn't recognise my password - and when I try to get a new password it says "Username not found" (but not that there is no account with this name). Please help!

Yuri

**Comment by carlosmondra** [comment]
Hello @yuri-bizzoni 

I removed your email from the issue, but I was not able to find an account associated to that email. You need to sign up first: https://openreview.net/signup

If you continue to face problems, please send us an email to info@openreview.net because your case requires you to share sensitive information.
