### ISSUE TITLE
Your activation is in process, please wait to receive a notification email.

### ISSUE THREAD

**Issue by xxllp** [openreview/openreview#92]
I have sign up with gmail and outlook email,but  after  complete your signup for the OpenReview account
 I still can't login in with the error "Your activation is in process, please wait to receive a notification email."

what is the problems~~~~

**Comment by xxllp** [comment]
Your OpenReview profile has been successfully created. Please allow up to 12 hours before the profile is activated.

what is mean ,I try login one day later but also fail~~

**Comment by racheljsmart** [comment]
Your profile was rejected twice in moderation because the homepage you provided does not include your name or any information matching your education/career listed in your OpenReview profile. Two "OpenReview profile activation status" messages were delivered relaying this information. Please provide a homepage matching your name to verify your identity so we can activate your profile.
